#ifndef DUPLICATION_ACTIVATION_F1AP_MIR_H
#define DUPLICATION_ACTIVATION_F1AP_MIR_H

// 9.3.1.36
typedef enum{

  ACTIVE_DUPLICATION_ACT_F1AP,
  INACTIVE_DUPLICATION_ACT_F1AP,
  END_DUPLICATION_ACT_F1AP

} duplication_act_f1ap_e;

#endif

