#ifndef LONG_DRX_CYCLE_LENGTH_MIR_H
#define LONG_DRX_CYCLE_LENGTH_MIR_H 

// This IE is defined in TS 38.331 [8]

typedef enum {

  MS10_LONG_DRX_CYCLE_LEN = 0, 
  MS20_LONG_DRX_CYCLE_LEN, 
  MS32_LONG_DRX_CYCLE_LEN, 
  MS40_LONG_DRX_CYCLE_LEN,
  MS60_LONG_DRX_CYCLE_LEN, 
  MS64_LONG_DRX_CYCLE_LEN, 
  MS70_LONG_DRX_CYCLE_LEN, 
  MS80_LONG_DRX_CYCLE_LEN,
  MS128_LONG_DRX_CYCLE_LEN, 
  MS160_LONG_DRX_CYCLE_LEN, 
  MS256_LONG_DRX_CYCLE_LEN,
  MS320_LONG_DRX_CYCLE_LEN, 
  MS512_LONG_DRX_CYCLE_LEN, 
  MS640_LONG_DRX_CYCLE_LEN,
  MS1024_LONG_DRX_CYCLE_LEN, 
  MS1280_LONG_DRX_CYCLE_LEN,
  MS2048_LONG_DRX_CYCLE_LEN,
  MS2560_LONG_DRX_CYCLE_LEN, 
  MS5120_LONG_DRX_CYCLE_LEN,
  MS10240_LONG_DRX_CYCLE_LEN,

  END_LONG_DRX_CYCLE_LEN

} long_drx_cycle_len_e ;


#endif

