#ifndef MISC_CAUSE_F1AP_MIR_H
#define  MISC_CAUSE_F1AP_MIR_H


typedef enum{
  CONTROL_PROCESSING_OVERLOAD_MISC_CAUSE_F1AP = 0,
  NOT_ENOUGH_USER_PLANE_PROCESSING_RESOURCES_MISC_CAUSE_F1AP = 1,
  HARDWARE_FAILURE_MISC_CAUSE_F1AP = 2,
  OM_INTERVENTION_MISC_CAUSE_F1AP = 3,
  UNSPECIFIED_MISC_CAUSE_F1AP = 4,

  END_MISC_CAUSE_F1AP = 5,

} misc_cause_f1ap_e;

#endif


