#ifndef PROCEDURE_CRITICALLITY_F1AP_MIR_H
#define PROCEDURE_CRITICALLITY_F1AP_MIR_H

typedef enum {

  REJECT_PROCEDURE_CRITICALLITY_F1AP = 0,
  IGNORE_PROCEDURE_CRITICALLITY_F1AP = 1,
  NOTIFY_PROCEDURE_CRITICALLITY_F1AP = 2,

  END_PROCEDURE_CRITICALLITY_F1AP = 3,

} proc_crit_e;

#endif

