#ifndef RADIO_NETWORK_CAUSE_F1AP_MIR_H
#define  RADIO_NETWORK_CAUSE_F1AP_MIR_H


typedef enum{
  UNSPECIFIED_RADIO_NETWORK_CAUSE_F1AP = 0,
  RL_FAILURE_RLC__RADIO_NETWORK_CAUSE_F1AP = 1,
  UNKNOWN_OR_ALREADY_ALLOCATED_GNB_CU_UE_RADIO_NETWORK_CAUSE_F1AP = 2,
  UNKNOWN_OR_ALREADY_ALLOCATED_GNB_DU_UE_RADIO_NETWORK_CAUSE_F1AP = 3,
  UNKNOWN_OR_INCONSISTENT_PAIR_OF_UE_RADIO_NETWORK_CAUSE_F1AP = 4,
  INTERACTION_WITH_OTHER_PROCEDURE_RADIO_NETWORK_CAUSE_F1AP = 5,
  NOT_SUPPORTED_QCI_VALUE_RADIO_NETWORK_CAUSE_F1AP = 6,
  ACTION_DESIDERABLE_FOR_RADIO_REASONS_RADIO_NETWORK_CAUSE_F1AP = 7,
  NO_RADIO_RESOURCES_AVAILABLE_RADIO_NETWORK_CAUSE_F1AP = 8,
  PROCEDURE_CANCELLED_RADIO_NETWORK_CAUSE_F1AP = 9,
  NORMAL_RELEASE_RADIO_NETWORK_CAUSE_F1AP = 10,
  CELL_NOT_AVAILABLE_RADIO_NETWORK_CAUSE_F1AP = 11,
  RL_FAILURE_OTHERS_RADIO_NETWORK_CAUSE_F1AP = 12,
  UE_REJECTION_RADIO_NETWORK_CAUSE_F1AP = 13,
  RESOURCES_NOT_AVAILABLE_FOR_SLICE_RADIO_NETWORK_CAUSE_F1AP = 14,
  AMF_INITIATED_ABNORMAL_RELEASE_RADIO_NETWORK_CAUSE_F1AP = 15,
  RELEASE_DUE_TO_PRE_EMPTION_RADIO_NETWORK_CAUSE_F1AP = 16,
  _PLMN_NOT_SERVED_BY_THE_GNB_CU_RADIO_NETWORK_CAUSE_F1AP = 17,
  MULTIPLE_DRB_ID_INSTANCES_RADIO_NETWORK_CAUSE_F1AP = 18,
  UNKNOWN_DRB_ID_RADIO_NETWORK_CAUSE_F1AP = 19,


  MULTIPLE_BH_RLC_CH_ID_INSTANCES_RADIO_NETWORK_CAUSE_F1AP = 20,
  UNKNOWN_BH_RLC_CH_ID_RADIO_NETWORK_CAUSE_F1AP = 21,
  CHO_CPC_RESOURCES_TOBECHANGED_RADIO_NETWORK_CAUSE_F1AP = 22,
  NPN_NOT_SUPPORTED_RADIO_NETWORK_CAUSE_F1AP = 23,
  NPN_ACCESS_DENIED__RADIO_NETWORK_CAUSE_F1AP = 24,
  GNB_CU_CELL_CAPACITY_EXCEEDED_RADIO_NETWORK_CAUSE_F1AP = 25,
  REPORT_CHARACTERISTICS_EMPTY_RADIO_NETWORK_CAUSE_F1AP = 26,
  EXISTING_MEASUREMENT_ID_RADIO_NETWORK_CAUSE_F1AP = 27,
  MEASUREMENT_TEMPORARILY_NOT_AVAILABLE_RADIO_NETWORK_CAUSE_F1AP = 28,
  MEASUREMENT_NOT_SUPPORTED_FOR_THE_OBJECT_RADIO_NETWORK_CAUSE_F1AP = 29,

  END_RADIO_NETWORK_CAUSE_F1AP = 30

} radio_network_cause_f1ap_e ;

#endif

