#ifndef RLC_MODE_F1AP_MIR_H
#define RLC_MODE_F1AP_MIR_H 

// 9.3.1.27
typedef enum{

  RLC_AM_RLC_MODE_F1AP = 0, 
  RLC_UM_BIDIRECTIONAL_RLC_MODE_F1AP, 
  RLC_UM_UNIDIRECTIONAL_UL_RLC_MODE_F1AP,
  RLC_UM_UNIDIRECTIONAL_DL_RLC_MODE_F1AP,

  END_RLC_MODE_F1AP,

} rlc_mode_f1ap_e ;

#endif
