#ifndef SHORT_DRX_CYCLE_LEN_MIR_H
#define SHORT_DRX_CYCLE_LEN_MIR_H 

typedef enum{

  MS2_SHORT_DRX_CYCLE_LEN = 0, 
  MS3_SHORT_DRX_CYCLE_LEN,
  MS4_SHORT_DRX_CYCLE_LEN, 
  MS5_SHORT_DRX_CYCLE_LEN, 
  MS6_SHORT_DRX_CYCLE_LEN, 
  MS7_SHORT_DRX_CYCLE_LEN, 
  MS8_SHORT_DRX_CYCLE_LEN,
  MS10_SHORT_DRX_CYCLE_LEN, 
  MS14_SHORT_DRX_CYCLE_LEN, 
  MS16_SHORT_DRX_CYCLE_LEN, 
  MS20_SHORT_DRX_CYCLE_LEN,
  MS30_SHORT_DRX_CYCLE_LEN, 
  MS32_SHORT_DRX_CYCLE_LEN, 
  MS35_SHORT_DRX_CYCLE_LEN, 
  MS40_SHORT_DRX_CYCLE_LEN,
  MS64_SHORT_DRX_CYCLE_LEN, 
  MS80_SHORT_DRX_CYCLE_LEN, 
  MS128_SHORT_DRX_CYCLE_LEN, 
  MS160_SHORT_DRX_CYCLE_LEN,
  MS256_SHORT_DRX_CYCLE_LEN, 
  MS320_SHORT_DRX_CYCLE_LEN, 
  MS512_SHORT_DRX_CYCLE_LEN,
  MS640_SHORT_DRX_CYCLE_LEN,

  END_SHORT_DRX_CYCLE_LEN

} short_drx_cycle_len_e;


#endif

