#ifndef TRANSPORT_CAUSE_F1AP_MIR_H
#define TRANSPORT_CAUSE_F1AP_MIR_H 

typedef enum{
  UNSPECIFIED_TRANSPORT_CAUSE_F1AP = 0,
  RESOURCE_UNAVAILABLE_TRANSPORT_CAUSE_F1AP = 1,
  UNKNOWN_TNL_ADDRESS_FOR_IAB_TRANSPORT_CAUSE_F1AP = 2,
  UNKNOWN_UP_TNL_INFORMATION_FOR_IAB_TRANSPORT_CAUSE_F1AP = 3,

  END_TRANSPORT_CAUSE_F1AP = 4

} transport_cause_f1ap_e;



#endif

