#ifndef TRIGGERING_MESSAGE_F1AP_MIR_H
#define TRIGGERING_MESSAGE_F1AP_MIR_H 

typedef enum {

 INITIATING_MESSAGE_TRIGGERING_MESSAGE_F1AP = 0,
 SUCCESSFUL_OUTCOME_TRIGGERING_MESSAGE_F1AP = 1,
 UNSUCCESSFUL_OUTCOME_TRIGGERING_MESSAGE_F1AP = 2,

 END_TRIGGERING_MESSAGE_F1AP =3,

} trig_msg_e;

#endif

