set(E2SM_KPMv2_GRAMMAR e2sm-kpmv2.02.asn1)

set(e2sm_kpm_source
    asn_application.c
    asn_bit_data.c
    asn_codecs_prim.c
    asn_internal.c
    asn_random_fill.c
    asn_SEQUENCE_OF.c
    asn_SET_OF.c
    ber_decoder.c
    ber_tlv_length.c
    ber_tlv_tag.c
    BIT_STRING.c
    BOOLEAN.c
    constraints.c
    constr_CHOICE.c
    constr_SEQUENCE.c
    constr_SEQUENCE_OF.c
    constr_SET_OF.c
    constr_TYPE.c
    der_encoder.c
    E2SM_KPMv2_AMFPointer.c
    E2SM_KPMv2_AMFRegionID.c
    E2SM_KPMv2_AMFSetID.c
    E2SM_KPMv2_AMF-UE-NGAP-ID.c
    E2SM_KPMv2_CGI.c
    E2SM_KPMv2_CoreCPID.c
    E2SM_KPMv2_E2SM-KPM-ActionDefinition.c
    E2SM_KPMv2_E2SM-KPM-ActionDefinition-Format1.c
    E2SM_KPMv2_E2SM-KPM-ActionDefinition-Format2.c
    E2SM_KPMv2_E2SM-KPM-ActionDefinition-Format3.c
    E2SM_KPMv2_E2SM-KPM-ActionDefinition-Format4.c
    E2SM_KPMv2_E2SM-KPM-ActionDefinition-Format5.c
    E2SM_KPMv2_E2SM-KPM-EventTriggerDefinition.c
    E2SM_KPMv2_E2SM-KPM-EventTriggerDefinition-Format1.c
    E2SM_KPMv2_E2SM-KPM-IndicationHeader.c
    E2SM_KPMv2_E2SM-KPM-IndicationHeader-Format1.c
    E2SM_KPMv2_E2SM-KPM-IndicationMessage.c
    E2SM_KPMv2_E2SM-KPM-IndicationMessage-Format1.c
    E2SM_KPMv2_E2SM-KPM-IndicationMessage-Format2.c
    E2SM_KPMv2_E2SM-KPM-IndicationMessage-Format3.c
    E2SM_KPMv2_E2SM-KPM-RANfunction-Description.c
    E2SM_KPMv2_ENB-ID.c
    E2SM_KPMv2_ENB-UE-X2AP-ID.c
    E2SM_KPMv2_ENB-UE-X2AP-ID-Extension.c
    E2SM_KPMv2_EN-GNB-ID.c
    E2SM_KPMv2_E-UTRA-ARFCN.c
    E2SM_KPMv2_EUTRACellIdentity.c
    E2SM_KPMv2_EUTRA-CGI.c
    E2SM_KPMv2_E-UTRA-PCI.c
    E2SM_KPMv2_E-UTRA-TAC.c
    E2SM_KPMv2_FiveGS-TAC.c
    E2SM_KPMv2_FiveQI.c
    E2SM_KPMv2_FreqBandNrItem.c
    E2SM_KPMv2_GlobalENB-ID.c
    E2SM_KPMv2_GlobalenGNB-ID.c
    E2SM_KPMv2_GlobalGNB-ID.c
    E2SM_KPMv2_GlobalNgENB-ID.c
    E2SM_KPMv2_GlobalNGRANNodeID.c
    E2SM_KPMv2_GNB-CU-CP-UE-E1AP-ID.c
    E2SM_KPMv2_GNB-CU-UE-F1AP-ID.c
    E2SM_KPMv2_GNB-CU-UP-ID.c
    E2SM_KPMv2_GNB-DU-ID.c
    E2SM_KPMv2_GNB-ID.c
    E2SM_KPMv2_GranularityPeriod.c
    E2SM_KPMv2_GroupID.c
    E2SM_KPMv2_GUAMI.c
    E2SM_KPMv2_GUMMEI.c
    E2SM_KPMv2_IndexToRFSP.c
    E2SM_KPMv2_InterfaceID-E1.c
    E2SM_KPMv2_InterfaceIdentifier.c
    E2SM_KPMv2_InterfaceID-F1.c
    E2SM_KPMv2_InterfaceID-NG.c
    E2SM_KPMv2_InterfaceID-S1.c
    E2SM_KPMv2_InterfaceID-W1.c
    E2SM_KPMv2_InterfaceID-X2.c
    E2SM_KPMv2_InterfaceID-Xn.c
    E2SM_KPMv2_Interface-MessageID.c
    E2SM_KPMv2_InterfaceType.c
    E2SM_KPMv2_LabelInfoItem.c
    E2SM_KPMv2_LabelInfoList.c
    E2SM_KPMv2_MatchingCondItem.c
    E2SM_KPMv2_MatchingCondList.c
    E2SM_KPMv2_MatchingUeCondPerSubItem.c
    E2SM_KPMv2_MatchingUeCondPerSubList.c
    E2SM_KPMv2_MatchingUEidItem.c
    E2SM_KPMv2_MatchingUEidList.c
    E2SM_KPMv2_MatchingUEidPerSubItem.c
    E2SM_KPMv2_MatchingUEidPerSubList.c
    E2SM_KPMv2_MeasurementCondItem.c
    E2SM_KPMv2_MeasurementCondList.c
    E2SM_KPMv2_MeasurementCondUEidItem.c
    E2SM_KPMv2_MeasurementCondUEidList.c
    E2SM_KPMv2_MeasurementData.c
    E2SM_KPMv2_MeasurementDataItem.c
    E2SM_KPMv2_MeasurementInfo-Action-Item.c
    E2SM_KPMv2_MeasurementInfo-Action-List.c
    E2SM_KPMv2_MeasurementInfoItem.c
    E2SM_KPMv2_MeasurementInfoList.c
    E2SM_KPMv2_MeasurementLabel.c
    E2SM_KPMv2_MeasurementRecord.c
    E2SM_KPMv2_MeasurementRecordItem.c
    E2SM_KPMv2_MeasurementType.c
    E2SM_KPMv2_MeasurementTypeID.c
    E2SM_KPMv2_MeasurementTypeName.c
    E2SM_KPMv2_MME-Code.c
    E2SM_KPMv2_MME-Group-ID.c
    E2SM_KPMv2_MME-UE-S1AP-ID.c
    E2SM_KPMv2_NGENB-CU-UE-W1AP-ID.c
    E2SM_KPMv2_NGENB-DU-ID.c
    E2SM_KPMv2_NgENB-ID.c
    E2SM_KPMv2_NG-RANnodeUEXnAPID.c
    E2SM_KPMv2_NR-ARFCN.c
    E2SM_KPMv2_NRCellIdentity.c
    E2SM_KPMv2_NR-CGI.c
    E2SM_KPMv2_NRFrequencyBandItem.c
    E2SM_KPMv2_NRFrequencyBand-List.c
    E2SM_KPMv2_NRFrequencyInfo.c
    E2SM_KPMv2_NRFrequencyShift7p5khz.c
    E2SM_KPMv2_NR-PCI.c
    E2SM_KPMv2_PLMNIdentity.c
    E2SM_KPMv2_QCI.c
    E2SM_KPMv2_QosFlowIdentifier.c
    E2SM_KPMv2_QoSID.c
    E2SM_KPMv2_RANfunction-Name.c
    E2SM_KPMv2_RANUEID.c
    E2SM_KPMv2_RIC-EventTriggerStyle-Item.c
    E2SM_KPMv2_RIC-Format-Type.c
    E2SM_KPMv2_RIC-ReportStyle-Item.c
    E2SM_KPMv2_RIC-Style-Name.c
    E2SM_KPMv2_RIC-Style-Type.c
    E2SM_KPMv2_RRCclass-LTE.c
    E2SM_KPMv2_RRCclass-NR.c
    E2SM_KPMv2_RRC-MessageID.c
    E2SM_KPMv2_SD.c
    E2SM_KPMv2_ServingCell-ARFCN.c
    E2SM_KPMv2_ServingCell-PCI.c
    E2SM_KPMv2_S-NSSAI.c
    E2SM_KPMv2_SST.c
    E2SM_KPMv2_SubscriberProfileIDforRFP.c
    E2SM_KPMv2_SupportedSULBandList.c
    E2SM_KPMv2_SupportedSULFreqBandItem.c
    E2SM_KPMv2_TestCond-Expression.c
    E2SM_KPMv2_TestCondInfo.c
    E2SM_KPMv2_TestCond-Type.c
    E2SM_KPMv2_TestCond-Value.c
    E2SM_KPMv2_TimeStamp.c
    E2SM_KPMv2_UEID.c
    E2SM_KPMv2_UEID-ENB.c
    E2SM_KPMv2_UEID-EN-GNB.c
    E2SM_KPMv2_UEID-GNB.c
    E2SM_KPMv2_UEID-GNB-CU-CP-E1AP-ID-Item.c
    E2SM_KPMv2_UEID-GNB-CU-CP-E1AP-ID-List.c
    E2SM_KPMv2_UEID-GNB-CU-CP-F1AP-ID-Item.c
    E2SM_KPMv2_UEID-GNB-CU-F1AP-ID-List.c
    E2SM_KPMv2_UEID-GNB-CU-UP.c
    E2SM_KPMv2_UEID-GNB-DU.c
    E2SM_KPMv2_UEID-NG-ENB.c
    E2SM_KPMv2_UEID-NG-ENB-DU.c
    E2SM_KPMv2_UEMeasurementReportItem.c
    E2SM_KPMv2_UEMeasurementReportList.c
    INTEGER.c
    NativeEnumerated.c
    NativeInteger.c
    NativeReal.c
    NULL.c
    OCTET_STRING.c
    OPEN_TYPE.c
    per_decoder.c
    per_encoder.c
    per_opentype.c
    per_support.c
    PrintableString.c
    REAL.c
    xer_decoder.c
    xer_encoder.c
    xer_support.c
)

set(e2sm_kpm_headers
    asn_application.h
    asn_bit_data.h
    asn_codecs.h
    asn_codecs_prim.h
    asn_internal.h
    asn_ioc.h
    asn_random_fill.h
    asn_SEQUENCE_OF.h
    asn_SET_OF.h
    asn_system.h
    ber_decoder.h
    ber_tlv_length.h
    ber_tlv_tag.h
    BIT_STRING.h
    BOOLEAN.h
    constraints.h
    constr_CHOICE.h
    constr_SEQUENCE.h
    constr_SEQUENCE_OF.h
    constr_SET_OF.h
    constr_TYPE.h
    der_encoder.h
    E2SM_KPMv2_AMFPointer.h
    E2SM_KPMv2_AMFRegionID.h
    E2SM_KPMv2_AMFSetID.h
    E2SM_KPMv2_AMF-UE-NGAP-ID.h
    E2SM_KPMv2_asn_constant.h
    E2SM_KPMv2_CGI.h
    E2SM_KPMv2_CoreCPID.h
    E2SM_KPMv2_E2SM-KPM-ActionDefinition-Format1.h
    E2SM_KPMv2_E2SM-KPM-ActionDefinition-Format2.h
    E2SM_KPMv2_E2SM-KPM-ActionDefinition-Format3.h
    E2SM_KPMv2_E2SM-KPM-ActionDefinition-Format4.h
    E2SM_KPMv2_E2SM-KPM-ActionDefinition-Format5.h
    E2SM_KPMv2_E2SM-KPM-ActionDefinition.h
    E2SM_KPMv2_E2SM-KPM-EventTriggerDefinition-Format1.h
    E2SM_KPMv2_E2SM-KPM-EventTriggerDefinition.h
    E2SM_KPMv2_E2SM-KPM-IndicationHeader-Format1.h
    E2SM_KPMv2_E2SM-KPM-IndicationHeader.h
    E2SM_KPMv2_E2SM-KPM-IndicationMessage-Format1.h
    E2SM_KPMv2_E2SM-KPM-IndicationMessage-Format2.h
    E2SM_KPMv2_E2SM-KPM-IndicationMessage-Format3.h
    E2SM_KPMv2_E2SM-KPM-IndicationMessage.h
    E2SM_KPMv2_E2SM-KPM-RANfunction-Description.h
    E2SM_KPMv2_ENB-ID.h
    E2SM_KPMv2_ENB-UE-X2AP-ID-Extension.h
    E2SM_KPMv2_ENB-UE-X2AP-ID.h
    E2SM_KPMv2_EN-GNB-ID.h
    E2SM_KPMv2_E-UTRA-ARFCN.h
    E2SM_KPMv2_EUTRACellIdentity.h
    E2SM_KPMv2_EUTRA-CGI.h
    E2SM_KPMv2_E-UTRA-PCI.h
    E2SM_KPMv2_E-UTRA-TAC.h
    E2SM_KPMv2_FiveGS-TAC.h
    E2SM_KPMv2_FiveQI.h
    E2SM_KPMv2_FreqBandNrItem.h
    E2SM_KPMv2_GlobalENB-ID.h
    E2SM_KPMv2_GlobalenGNB-ID.h
    E2SM_KPMv2_GlobalGNB-ID.h
    E2SM_KPMv2_GlobalNgENB-ID.h
    E2SM_KPMv2_GlobalNGRANNodeID.h
    E2SM_KPMv2_GNB-CU-CP-UE-E1AP-ID.h
    E2SM_KPMv2_GNB-CU-UE-F1AP-ID.h
    E2SM_KPMv2_GNB-CU-UP-ID.h
    E2SM_KPMv2_GNB-DU-ID.h
    E2SM_KPMv2_GNB-ID.h
    E2SM_KPMv2_GranularityPeriod.h
    E2SM_KPMv2_GroupID.h
    E2SM_KPMv2_GUAMI.h
    E2SM_KPMv2_GUMMEI.h
    E2SM_KPMv2_IndexToRFSP.h
    E2SM_KPMv2_InterfaceID-E1.h
    E2SM_KPMv2_InterfaceIdentifier.h
    E2SM_KPMv2_InterfaceID-F1.h
    E2SM_KPMv2_InterfaceID-NG.h
    E2SM_KPMv2_InterfaceID-S1.h
    E2SM_KPMv2_InterfaceID-W1.h
    E2SM_KPMv2_InterfaceID-X2.h
    E2SM_KPMv2_InterfaceID-Xn.h
    E2SM_KPMv2_Interface-MessageID.h
    E2SM_KPMv2_InterfaceType.h
    E2SM_KPMv2_LabelInfoItem.h
    E2SM_KPMv2_LabelInfoList.h
    E2SM_KPMv2_MatchingCondItem.h
    E2SM_KPMv2_MatchingCondList.h
    E2SM_KPMv2_MatchingUeCondPerSubItem.h
    E2SM_KPMv2_MatchingUeCondPerSubList.h
    E2SM_KPMv2_MatchingUEidItem.h
    E2SM_KPMv2_MatchingUEidList.h
    E2SM_KPMv2_MatchingUEidPerSubItem.h
    E2SM_KPMv2_MatchingUEidPerSubList.h
    E2SM_KPMv2_MeasurementCondItem.h
    E2SM_KPMv2_MeasurementCondList.h
    E2SM_KPMv2_MeasurementCondUEidItem.h
    E2SM_KPMv2_MeasurementCondUEidList.h
    E2SM_KPMv2_MeasurementData.h
    E2SM_KPMv2_MeasurementDataItem.h
    E2SM_KPMv2_MeasurementInfo-Action-Item.h
    E2SM_KPMv2_MeasurementInfo-Action-List.h
    E2SM_KPMv2_MeasurementInfoItem.h
    E2SM_KPMv2_MeasurementInfoList.h
    E2SM_KPMv2_MeasurementLabel.h
    E2SM_KPMv2_MeasurementRecord.h
    E2SM_KPMv2_MeasurementRecordItem.h
    E2SM_KPMv2_MeasurementType.h
    E2SM_KPMv2_MeasurementTypeID.h
    E2SM_KPMv2_MeasurementTypeName.h
    E2SM_KPMv2_MME-Code.h
    E2SM_KPMv2_MME-Group-ID.h
    E2SM_KPMv2_MME-UE-S1AP-ID.h
    E2SM_KPMv2_NGENB-CU-UE-W1AP-ID.h
    E2SM_KPMv2_NGENB-DU-ID.h
    E2SM_KPMv2_NgENB-ID.h
    E2SM_KPMv2_NG-RANnodeUEXnAPID.h
    E2SM_KPMv2_NR-ARFCN.h
    E2SM_KPMv2_NRCellIdentity.h
    E2SM_KPMv2_NR-CGI.h
    E2SM_KPMv2_NRFrequencyBandItem.h
    E2SM_KPMv2_NRFrequencyBand-List.h
    E2SM_KPMv2_NRFrequencyInfo.h
    E2SM_KPMv2_NRFrequencyShift7p5khz.h
    E2SM_KPMv2_NR-PCI.h
    E2SM_KPMv2_PLMNIdentity.h
    E2SM_KPMv2_QCI.h
    E2SM_KPMv2_QosFlowIdentifier.h
    E2SM_KPMv2_QoSID.h
    E2SM_KPMv2_RANfunction-Name.h
    E2SM_KPMv2_RANUEID.h
    E2SM_KPMv2_RIC-EventTriggerStyle-Item.h
    E2SM_KPMv2_RIC-Format-Type.h
    E2SM_KPMv2_RIC-ReportStyle-Item.h
    E2SM_KPMv2_RIC-Style-Name.h
    E2SM_KPMv2_RIC-Style-Type.h
    E2SM_KPMv2_RRCclass-LTE.h
    E2SM_KPMv2_RRCclass-NR.h
    E2SM_KPMv2_RRC-MessageID.h
    E2SM_KPMv2_SD.h
    E2SM_KPMv2_ServingCell-ARFCN.h
    E2SM_KPMv2_ServingCell-PCI.h
    E2SM_KPMv2_S-NSSAI.h
    E2SM_KPMv2_SST.h
    E2SM_KPMv2_SubscriberProfileIDforRFP.h
    E2SM_KPMv2_SupportedSULBandList.h
    E2SM_KPMv2_SupportedSULFreqBandItem.h
    E2SM_KPMv2_TestCond-Expression.h
    E2SM_KPMv2_TestCondInfo.h
    E2SM_KPMv2_TestCond-Type.h
    E2SM_KPMv2_TestCond-Value.h
    E2SM_KPMv2_TimeStamp.h
    E2SM_KPMv2_UEID-ENB.h
    E2SM_KPMv2_UEID-EN-GNB.h
    E2SM_KPMv2_UEID-GNB-CU-CP-E1AP-ID-Item.h
    E2SM_KPMv2_UEID-GNB-CU-CP-E1AP-ID-List.h
    E2SM_KPMv2_UEID-GNB-CU-CP-F1AP-ID-Item.h
    E2SM_KPMv2_UEID-GNB-CU-F1AP-ID-List.h
    E2SM_KPMv2_UEID-GNB-CU-UP.h
    E2SM_KPMv2_UEID-GNB-DU.h
    E2SM_KPMv2_UEID-GNB.h
    E2SM_KPMv2_UEID.h
    E2SM_KPMv2_UEID-NG-ENB-DU.h
    E2SM_KPMv2_UEID-NG-ENB.h
    E2SM_KPMv2_UEMeasurementReportItem.h
    E2SM_KPMv2_UEMeasurementReportList.h
    INTEGER.h
    NativeEnumerated.h
    NativeInteger.h
    NativeReal.h
    NULL.h
    OCTET_STRING.h
    OPEN_TYPE.h
    per_decoder.h
    per_encoder.h
    per_opentype.h
    per_support.h
    PrintableString.h
    REAL.h
    xer_decoder.h
    xer_encoder.h
    xer_support.h
)
